import React, { useState, useEffect } from "react";
import { FiShield, FiCalendar, FiFileText } from "react-icons/fi";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { getTermsAndConditions } from "../api/Legal";
import "../styles/LegalPage.css";

const FALLBACK_TERMS_CONTENT = `FacilityCore Terms & Conditions
Last Updated: July 20, 2026
Welcome to FacilityCore. These Terms & Conditions ("Terms") govern your access to and use of the FacilityCore web application, mobile application, APIs, and related services (collectively, the "Platform"). By creating an account, accessing, or using FacilityCore, you agree to be bound by these Terms.
If you do not agree with these Terms, you must not use the Platform.
 
1. Definitions
For the purpose of these Terms:
•\tFacilityCore refers to the software platform, its website, mobile applications, services, APIs, and all related products.
•\tCompany refers to the organization or individual registering and subscribing to FacilityCore.
•\tAdministrator refers to the authorized person responsible for managing the Company's account.
•\tUsers include administrators, employees, contractors, vendors, residents, occupants, visitors, and any authorized personnel using the Platform.
•\tCustomer Data means all information uploaded or generated by the Customer while using the Platform.
•\tConfidential Information means any non-public information exchanged between the Customer and FacilityCore.
 
2. Acceptance of Terms
By registering an account, you confirm that:
•\tYou are at least 18 years old.
•\tYou have the authority to represent your organization.
•\tAll registration information provided is accurate.
•\tYou agree to comply with applicable laws and regulations.
 
3. User Registration
The Customer agrees to:
•\tProvide accurate company information.
•\tMaintain current contact information.
•\tKeep login credentials confidential.
•\tNotify FacilityCore immediately of unauthorized account access.
•\tEnsure all users comply with these Terms.
The Customer is fully responsible for all activities performed under its account.
 
4. Subscription & Billing
Subscription plans may include:
•\tMonthly Plans
•\tAnnual Plans
•\tEnterprise Plans
Subscriptions automatically renew unless cancelled before the renewal date.
Failure to pay subscription fees may result in suspension or termination of services.
 
5. Free Trial
If a free trial is offered:
•\tTrial access is limited to the advertised duration.
•\tCertain features may be restricted.
•\tFacilityCore may terminate the trial at any time.
•\tNo refunds are applicable for expired trials.
 
6. Acceptable Use
Users agree NOT to:
•\tUpload illegal or harmful content.
•\tAttempt unauthorized access.
•\tReverse engineer the software.
•\tIntroduce malware or viruses.
•\tShare login credentials.
•\tUse the Platform for unlawful purposes.
•\tInterfere with Platform performance.
•\tCircumvent security measures.
Violation may result in immediate account suspension.
 
7. Customer Data Ownership
The Customer retains full ownership of:
•\tAsset information
•\tEmployee records
•\tResident information
•\tVendor information
•\tFinancial records
•\tMaintenance history
•\tDocuments
•\tImages
•\tVideos
•\tReports
•\tWork Orders
•\tInventory records
•\tCompliance records
•\tContracts
FacilityCore does not claim ownership of Customer Data.
 
8. Data Processing
FacilityCore processes Customer Data solely for:
•\tProviding Platform functionality
•\tTechnical support
•\tProduct improvements
•\tSystem monitoring
•\tBackup and disaster recovery
•\tSecurity monitoring
•\tPerformance optimization
 
9. Data Privacy
FacilityCore implements commercially reasonable security measures including:
•\tEncrypted communication (HTTPS/TLS)
•\tPassword encryption
•\tRole-based access control
•\tAudit logs
•\tSecure cloud infrastructure
•\tBackup procedures
While we strive to protect Customer Data, no internet-based service can guarantee absolute security.
 
10. Benchmarking & Operational Insights (Optional)
By enabling this option during signup or within your account settings, you voluntarily consent to securely share selected high-level operational metrics with FacilityCore.
These metrics may include aggregated and non-sensitive information such as:
•\tNumber of properties
•\tNumber of buildings
•\tTotal built-up area
•\tNumber of apartments or units
•\tOccupancy rates
•\tAsset counts by category
•\tPreventive maintenance completion rates
•\tReactive maintenance response times
•\tWork order volumes
•\tAsset downtime statistics
•\tCleaning task completion percentages
•\tCompliance completion rates
•\tHelpdesk performance metrics
•\tEnergy consumption summaries
•\tWater consumption summaries
•\tInventory usage summaries
•\tVendor performance indicators
•\tSLA achievement rates
•\tWorkforce productivity indicators
•\tDashboard usage statistics
•\tFeature adoption metrics
FacilityCore will use this information to provide:
•\tIndustry benchmarking insights
•\tPerformance comparisons against similar facilities
•\tPreventive maintenance recommendations
•\tOperational efficiency suggestions
•\tTechnical recommendations
•\tAsset lifecycle optimization guidance
•\tCustomer success guidance
•\tProduct improvement recommendations
•\tBest practice recommendations
•\tPredictive operational insights
FacilityCore will not disclose your organization's identity when producing aggregated benchmarking reports unless you provide explicit written consent.
Participation is entirely optional and may be withdrawn at any time through your account settings or by contacting FacilityCore support.
 
11. Anonymous Analytics
FacilityCore may collect anonymous usage statistics including:
•\tFeature usage
•\tSession duration
•\tDevice type
•\tBrowser information
•\tOperating system
•\tError logs
•\tPerformance metrics
This information is used solely to improve the Platform.
 
12. AI & Recommendation Services
FacilityCore may utilize artificial intelligence, machine learning, or rule-based analytics to generate:
•\tMaintenance recommendations
•\tAsset health insights
•\tRisk assessments
•\tEnergy optimization suggestions
•\tCleaning optimization
•\tWorkforce recommendations
•\tInventory forecasts
•\tBudget forecasting
•\tPredictive maintenance alerts
These recommendations are advisory only and should be reviewed by qualified personnel before implementation.
 
13. Confidentiality
FacilityCore agrees to maintain the confidentiality of Customer Data and shall not disclose it to third parties except:
•\tAs required by law.
•\tWith Customer authorization.
•\tTo trusted service providers bound by confidentiality obligations.
•\tTo protect legal rights and security.
 
14. Data Retention
Customer Data will be retained:
•\tDuring the active subscription.
•\tDuring any agreed retention period after cancellation.
•\tAs required by applicable laws.
FacilityCore may permanently delete Customer Data after the applicable retention period.
 
15. Customer Responsibilities
The Customer is responsible for:
•\tData accuracy
•\tUser permissions
•\tBackup of exported reports
•\tCompliance with local regulations
•\tMaintaining secure passwords
•\tTraining users
•\tReviewing AI-generated recommendations
 
16. Intellectual Property
FacilityCore retains all rights to:
•\tSoftware
•\tSource code
•\tDesign
•\tUser interface
•\tDocumentation
•\tLogos
•\tTrademarks
•\tAPIs
•\tAlgorithms
•\tReports
•\tTemplates
Customers receive a limited, non-transferable license to use the Platform during an active subscription.
 
17. Third-Party Services
FacilityCore may integrate with third-party services such as:
•\tGoogle Maps
•\tFirebase
•\tEmail providers
•\tSMS gateways
•\tPayment gateways
•\tCloud storage providers
•\tAuthentication providers
FacilityCore is not responsible for interruptions caused by third-party services.
 
18. Availability
FacilityCore aims for high service availability but does not guarantee uninterrupted operation.
Scheduled maintenance, emergency maintenance, or events beyond our reasonable control may temporarily affect service availability.
 
19. Limitation of Liability
To the maximum extent permitted by law, FacilityCore shall not be liable for:
•\tLoss of profits
•\tBusiness interruption
•\tData loss
•\tIndirect damages
•\tIncidental damages
•\tConsequential damages
The total liability shall not exceed the subscription fees paid during the twelve (12) months immediately preceding the claim.
 
20. Indemnification
The Customer agrees to indemnify and hold FacilityCore harmless from any claims arising from:
•\tMisuse of the Platform
•\tViolation of these Terms
•\tInfringement of third-party rights
•\tUnauthorized use of Customer accounts
 
21. Suspension & Termination
FacilityCore may suspend or terminate accounts for:
•\tNon-payment
•\tIllegal activities
•\tSecurity risks
•\tAbuse of services
•\tBreach of these Terms
The Customer may terminate the subscription according to the applicable cancellation policy.
 
22. Force Majeure
FacilityCore shall not be liable for delays or failures caused by events beyond reasonable control, including natural disasters, internet outages, government actions, pandemics, labor disputes, or cyberattacks.
 
23. Changes to the Terms
FacilityCore reserves the right to update these Terms from time to time. Material changes will be communicated through the Platform or by email. Continued use of the Platform after such changes constitutes acceptance of the revised Terms.
 
24. Governing Law
These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the competent courts in Chennai, Tamil Nadu, unless otherwise agreed in writing.
 
25. Contact Information
For questions regarding these Terms, privacy, or data protection, please contact:
FacilityCore Support
Email: support@facilitycore.in
Website: https://facilitycore.in`;

const formatInlineText = (text) => {
  if (!text) return "";

  // 1. Pre-sanitize text to strip markdown bold stars wrapped around links, URLs, or emails
  let cleanText = text
    .replace(/\*\*\s*(\[[^\]]+\]\([^)]+\))\s*\*\*/g, "$1")
    .replace(/\*\*\s*(https?:\/\/[^\s*]+)\s*\*\*/g, "$1")
    .replace(/\*\*\s*([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\s*\*\*/g, "$1");

  // 2. Parse markdown links [label](url) first
  const linkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
  const parts = [];
  let lastIndex = 0;
  let match;

  while ((match = linkRegex.exec(cleanText)) !== null) {
    const [fullMatch, label, url] = match;
    const startIndex = match.index;

    if (startIndex > lastIndex) {
      parts.push(cleanText.substring(lastIndex, startIndex));
    }

    const isMail = url.startsWith("mailto:");
    const cleanUrl = isMail ? url.replace(/^mailto:/, "") : url;
    parts.push(
      <a
        key={`mdlink-${startIndex}`}
        href={isMail ? `mailto:${cleanUrl}` : url}
        className="legal-link"
        target={isMail ? "_self" : "_blank"}
        rel={isMail ? undefined : "noopener noreferrer"}
      >
        {label}
      </a>
    );

    lastIndex = linkRegex.lastIndex;
  }

  if (lastIndex < cleanText.length) {
    parts.push(cleanText.substring(lastIndex));
  }

  // 3. For string parts, parse inline bold **text** or remaining URLs/emails
  return parts.map((part, pIdx) => {
    if (typeof part !== "string") return part;

    const boldRegex = /\*+([^*]+)\*+/g;
    const subParts = [];
    let subLastIndex = 0;
    let boldMatch;

    while ((boldMatch = boldRegex.exec(part)) !== null) {
      const [bFull, bText] = boldMatch;
      const bStart = boldMatch.index;

      if (bStart > subLastIndex) {
        subParts.push(part.substring(subLastIndex, bStart));
      }

      subParts.push(
        <strong key={`b-${bStart}`} className="legal-bold">
          {bText}
        </strong>
      );

      subLastIndex = boldRegex.lastIndex;
    }

    if (subLastIndex < part.length) {
      subParts.push(part.substring(subLastIndex));
    }

    // Strip any remaining lone asterisks in text nodes
    return subParts.map((subPart, sIdx) => {
      if (typeof subPart !== "string") return subPart;

      const sanitizedSub = subPart.replace(/\*/g, "");
      if (!sanitizedSub) return null;

      // Auto-link standalone URLs or Emails
      const urlEmailRegex = /(https?:\/\/[^\s<]+|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/g;
      const finalElements = [];
      let fLastIndex = 0;
      let fMatch;

      while ((fMatch = urlEmailRegex.exec(sanitizedSub)) !== null) {
        const [fFull] = fMatch;
        const fStart = fMatch.index;

        if (fStart > fLastIndex) {
          finalElements.push(sanitizedSub.substring(fLastIndex, fStart));
        }

        const isEmail = fFull.includes("@") && !fFull.startsWith("http");
        const href = isEmail ? `mailto:${fFull}` : fFull;

        finalElements.push(
          <a
            key={`autolink-${fStart}`}
            href={href}
            className="legal-link"
            target={isEmail ? "_self" : "_blank"}
            rel={isEmail ? undefined : "noopener noreferrer"}
          >
            {fFull}
          </a>
        );

        fLastIndex = urlEmailRegex.lastIndex;
      }

      if (fLastIndex < sanitizedSub.length) {
        finalElements.push(sanitizedSub.substring(fLastIndex));
      }

      return <React.Fragment key={`sub-${pIdx}-${sIdx}`}>{finalElements}</React.Fragment>;
    });
  });
};

const renderContent = (rawText) => {
  if (!rawText) return null;
  const lines = rawText.split("\n");
  const elements = [];
  let currentList = [];

  const flushList = (key) => {
    if (currentList.length > 0) {
      elements.push(
        <ul className="legal-ul" key={`${key}-list`}>
          {currentList.map((item, idx) => (
            <li className="legal-li" key={idx}>
              {item}
            </li>
          ))}
        </ul>
      );
      currentList = [];
    }
  };

  lines.forEach((line, idx) => {
    const trimmed = line.trim();
    if (!trimmed) {
      flushList(idx);
      return;
    }

    if (trimmed.startsWith("•") || trimmed.startsWith("*")) {
      const itemText = trimmed.replace(/^[•*]\s*/, "");
      currentList.push(formatInlineText(itemText));
      return;
    }

    flushList(idx);

    const cleanLine = trimmed.replace(/^\*+\s*/, "").replace(/\*+$/, "");

    if (/^\d+\.\s+/.test(trimmed) || /^[A-Z\s]{4,}$/.test(trimmed)) {
      elements.push(
        <h2 className="legal-h2" key={idx}>
          {formatInlineText(cleanLine)}
        </h2>
      );
    } else if (/^[A-Z]\.\s+/.test(trimmed)) {
      elements.push(
        <h3 className="legal-h3" key={idx}>
          {formatInlineText(cleanLine)}
        </h3>
      );
    } else {
      elements.push(
        <p className="legal-paragraph" key={idx}>
          {formatInlineText(trimmed)}
        </p>
      );
    }
  });

  flushList("end");
  return elements;
};

const TermsPage = () => {
  const [content, setContent] = useState(FALLBACK_TERMS_CONTENT);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;
    const fetchDoc = async () => {
      try {
        const res = await getTermsAndConditions();
        if (res && res.content && active) {
          setContent(res.content);
        }
      } catch (err) {
        console.error("Failed to fetch Terms & Conditions from API:", err);
      } finally {
        if (active) setLoading(false);
      }
    };

    fetchDoc();
    return () => {
      active = false;
    };
  }, []);

  return (
    <div className="legal-page-wrapper">
      <Navbar />

      {/* Hero Header */}
      <section className="legal-hero">
        <div className="legal-hero-container">
          <div className="legal-badge">
            <FiShield /> LEGAL DOCUMENTATION
          </div>
          <h1 className="legal-title">Terms & Conditions</h1>
          <div className="legal-meta">
            <div className="legal-meta-item">
              <FiCalendar /> Last Updated: July 20, 2026
            </div>
            <span>•</span>
            <div className="legal-meta-item">
              <FiFileText /> Official Policy
            </div>
          </div>
        </div>
      </section>

      {/* Main Body */}
      <section className="legal-content-section">
        <div className="legal-container">
          {loading ? (
            <div className="legal-loading">
              <div className="legal-spinner" />
              <span>Loading latest terms...</span>
            </div>
          ) : (
            <div className="legal-body">{renderContent(content)}</div>
          )}
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsPage;
